yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
# from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Ссылка на пост',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Ссылка на автора коммента',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        'Комментарий поста',
        help_text='Напишите комментарий'
    )
    created = models.DateTimeField(
        'Время написания комментария',
        auto_now_add=True
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_user_author',
            )
        ]

        def __str__(self):
            return self.user.username

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'image': ('Картинка в посте'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Follow
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from yatube.settings import SHOWED_POSTS
from django.views.decorators.cache import cache_page


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    # Если порядок сортировки определен в классе Meta модели,
    # запрос будет выглядить так:
    # post_list = Post.objects.all()
    # Показывать по 10 записей на странице.
    paginator = Paginator(post_list, 10)

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
    # Отдаем в словаре контекста
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    posts_count = author.posts.count()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': author,
        'posts_count': posts_count,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.select_related('author')
    group = post.group
    author = post.author
    posts_count = author.posts.count()
    context = {
        'post': post,
        'group': group,
        'posts_count': posts_count,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


def get_page_context(queryset, request):
    paginator = Paginator(queryset, SHOWED_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_number': page_number,
        'page_obj': page_obj,
    }


@login_required
def post_create(request):
    form = PostForm(
        request.POST,
        files=request.FILES or None
    )
    if request.method == "POST":
        # создаётся объект формы на основе класса PostForm
        # Если все данные формы валидны
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # создаём объект и отправляем в базу
            form.save()
            # перенапрвляем в профиль автора поста
            return redirect('posts:profile', post.author)
        # если данные не прошли валидаую, то
        return render(request, 'posts/create_post.html', {'form': form})
    # Если пришёл не POST запрос, создаём и передаём пустую форму
    return render(request, 'posts/create_post.html', {'form': form})


def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, id=post_id, author=request.user)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST':
        if form.is_valid():
            post = form.save()
            return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'post_id': post_id,
        'is_edit': is_edit,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Информация о текущем пользователе доступна в переменной request.user."""
    user = request.user
    post = Post.objects.filter(author__following__user=user)
    page_obj = get_page_context(post, request)
    context = {
        'post': post,
    }
    context.update(page_obj)
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    following = user.follower.filter(author=author)
    following.delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}  
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">  
              {% if is_edit %}
                Редактировать пост
              {% else %}  
                Новый пост
              {% endif %}  
            </div>
            <div class="card-body">
              {% if is_edit %}        
              <form method="POST" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id %}">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">            
              {% else %} 
              <form method="POST" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
              {% endif %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста                  
                    <span class="required text-danger" >*</span>                  
                  </label>
                    {% csrf_token %}
                    {{ form.text }}             
                  <small id="id_text-help" class="form-text text-muted">
                    {% if is_edit %}
                      Редактирование поста
                    {% else %}
                      Текст нового поста
                    {% endif %}
                  </small>                  
                </div>            
                <div class="form-group row my-3 p-3">
                  <label for="id_group">
                    Группа                  
                  </label>
                  <select name="group" class="form-control" id="id_group">
                    {% for group in form.group %}
                      {{ group }}
                    {% endfor %}
                  </select>
                  <small id="id_group-help" class="form-text text-muted">
                    Группа, к которой будет относиться пост
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  {% if is_edit %}
                    <label for="id_image">
                      Картинка                      
                    </label>
                    На данный момент: <a href={{ im.url }}>{{ im.url }}</a>
                    <input type="checkbox" name="image-clear" id="image-clear_id">
                    <label for="image-clear_id">Очистить</label><br>
                    Изменить:
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">  
                  {% else %}
                    <label for="id_image">
                      Картинка                      
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image"> 
                  {% endif %} 
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}               
                  </button> 
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}Посты авторов, на которых Вы подписаны{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <div class="container py-5"> 
    {% cache 20 index_page page_obj%} 
    {% for post in page_obj %}   
      {% include 'posts/includes/posts.html' %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock title %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'posts/includes/posts.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5"> 
    {% include 'posts/includes/switcher.html' %}
    {% cache 20 index_page page_obj%} 
    {% for post in page_obj %}   
      {% include 'posts/includes/posts.html' %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %} Пост {{ post.text }}[:30] {% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %} 
          <li class="list-group-item">
            Группа: {{ group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}  
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a> 
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post_id=post.pk %}">
        редактировать запись
      </a> 
    </article>
    {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}      
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
    {% endif %}
    {% for comment in comments %}
    <div class="media mb-4">
      <div class="media-body">
        <h5 class="mt-0">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
        </h5>
          <p>
            {{ comment.text|linebreaksbr }}
          </p>
        </div>
      </div>
    {% endfor %}
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ User.username }} {% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="mb-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ posts_count }} </h3>   
    <article>
      {% for post in page_obj %}
      {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
        <ul>
          <li>
            Автор: {{ author.get_full_name }}
            <a href="{% url 'posts:index' %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>       
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}